### ISSUE TITLE
Consider export code.google.com/p/go-charset

### ISSUE THREAD

**Issue by clsung** [ungerik/go-rss#10]
Since https://code.google.com/p/ is going to End-Of-Service, maybe consider to export go-charset to your github account?

- http://google-opensource.blogspot.tw/2015/03/farewell-to-google-code.html

**Comment by ungerik** [comment]
Will change it to this version on GitHub:
https://github.com/suapapa/go-charset

-Erik

On Thu, Jun 4, 2015 at 4:40 AM, Cheng-Lung Sung <notifications@github.com>
wrote:

> Since https://code.google.com/p/ is going to End-Of-Service, maybe
> consider to export go-charset to your github account?
>
>    -
>    http://google-opensource.blogspot.tw/2015/03/farewell-to-google-code.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ungerik/go-rss/issues/10>.
>



-- 
+43 650 58 33055
erik@erikunger.com
Skype: ungerik
http://erikunger.com
http://github.com/ungerik
http://twitter.com/ungerik
http://facebook.com/ungerik
http://www.linkedin.com/in/ungerik
http://www.xing.com/profile/Erik_Unger2

**Comment by clsung** [comment]
thanks

**Comment by ungerik** [comment]
Done

On Thu, Jun 4, 2015 at 8:07 AM, Erik Unger <erik@erikunger.com> wrote:

> Will change it to this version on GitHub:
> https://github.com/suapapa/go-charset
>
> -Erik
>
> On Thu, Jun 4, 2015 at 4:40 AM, Cheng-Lung Sung <notifications@github.com>
> wrote:
>
>> Since https://code.google.com/p/ is going to End-Of-Service, maybe
>> consider to export go-charset to your github account?
>>
>>    -
>>    http://google-opensource.blogspot.tw/2015/03/farewell-to-google-code.html
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ungerik/go-rss/issues/10>.
>>
>
>
>
> --
> +43 650 58 33055
> erik@erikunger.com
> Skype: ungerik
> http://erikunger.com
> http://github.com/ungerik
> http://twitter.com/ungerik
> http://facebook.com/ungerik
> http://www.linkedin.com/in/ungerik
> http://www.xing.com/profile/Erik_Unger2
>



-- 
+43 650 58 33055
erik@erikunger.com
Skype: ungerik
http://erikunger.com
http://github.com/ungerik
http://twitter.com/ungerik
http://facebook.com/ungerik
http://www.linkedin.com/in/ungerik
http://www.xing.com/profile/Erik_Unger2

**Comment by clsung** [comment]
thanks.
