### ISSUE TITLE
Support insecure read, without certificate check

### ISSUE THREAD

**Issue by zalalov** [ungerik/go-rss#13]

**Comment by 030** [comment]
Could you indicate whether you tried the `InsecureRead` function instead of the `Read` one?

**Comment by zalalov** [comment]
> Could you indicate whether you tried the `InsecureRead` function instead of the `Read` one?

yep, that's what I've added here:
https://github.com/ungerik/go-rss/pull/14

**Comment by zalalov** [comment]
so the one suppose to be solved :)

**Comment by 030** [comment]
@zalalov could you close the issue?
