### ISSUE TITLE
Unable to parse reddit atom feed

### ISSUE THREAD

**Issue by SuddenGunter** [ungerik/go-rss#18]
Try to parse
http://www.reddit.com/.rss
rss.Read returns empty struct with nil error. 
Can this library parse atom feeds?

How to reproduce:

```
v , err:= rss.Read("http://www.reddit.com/.rss")
```

Environment:
```
go version go1.12.8 linux/amd64
```

**Comment by 030** [comment]
https://www.reddit.com/r/redditdev/comments/5w60r1/error_429_too_many_requests_i_havent_made_many/de7ngx6/

Adding `--user-agent "curl:myappname:v0.0 (by /u/ocelost)"` to the curl request ensures that the reddit returns content. I will implement it.

**Comment by 030** [comment]
@SuddenGunter Could you test?

**Comment by SuddenGunter** [comment]
@030 tried using cod based on this https://github.com/ungerik/go-rss/blob/2f6706b577373dacdb1d6819334e9c8d89932ac4/example/main.go -  works good, thank you.
Although one thing I've noticed: not sure `reddit` is the correct name for variable at Read function - well, it's very specific imho. Mb should call it something like `sendUserAgent`
