### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by 030** [ungerik/go-rss#21]
Could you enable CI in for example travis-ci to ensure that the code get tested on every commit and could you add a build badge to the readme?

**Comment by 030** [comment]
@ungerik Could you indicate whether you will enable CI soon? I could submit a travis file, but then you have to enable CI in travis. I would like to enable it as well. Please let me know.

**Comment by ungerik** [comment]
@030 do you want to take ownership of the repo?
You seem very interested and I haven't used it for years.

**Comment by 030** [comment]
@ungerik That would be great.

**Comment by SuddenGunter** [comment]
@030 need help with CI?

**Comment by 030** [comment]
@SuddenGunter Please. Could you fix the unit tests and implement your suggestion? https://github.com/ungerik/go-rss/issues/18#issuecomment-612207801

**Comment by 030** [comment]
@ungerik could you add me as a maintainer of this repository?

**Comment by 030** [comment]
@SuddenGunter I will create a fork and let you know when it is available

**Comment by 030** [comment]
@SuddenGunter I created https://github.com/030/informado as I did not get any reply from ungerik anymore. We could start again and create features. CI is running. Please check whether it has to be changed and/or updated. Feel free to create issues and pull requests.

**Comment by 030** [comment]
@SuddenGunter https://github.com/030/informado
